# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_joint_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_joint_controller:
  ros__parameters:
    joints: [joint1, joint2, joint3, joint4, joint5, joint6]
    command_interfaces: [position]
    state_interfaces:   [position]
    allow_nonzero_velocity_at_trajectory_end: true

    state_publish_rate: 50.0
    action_monitor_rate: 20.0

#arm_velocity_controller:
  #type: velocity_controllers/JointGroupVelocityController
  #ros__parameters:
    #joints: [joint1, joint2, joint3, joint4, joint5, joint6]
    #command_interfaces: [velocity]
    #state_interfaces:   [velocity]